// var domain = "http://8.210.251.47";
var domain = "https://like288.com";
var language = window.localStorage.getItem("language");
console.log(language);
if(language == '' || language == 'null' || language == null){
language='vi';
window.localStorage.setItem("language",language);
}

var q_lang = {};


    
if(language == '' || language == 'cn' || language == null || language == 'null'){
	q_lang['cn'] = {
		'恭喜会员':'恭喜会员',
		'获得':'获得',
		'推广奖励':'推广奖励',
		'恭喜':'恭喜',
		'完成':'完成',
		'每日任务次数':'每日任务次数',
		'可领取任务总数':'可领取任务总数',
		'会员榜单提示':'会员榜单提示',
		'注册人数':'注册人数',
		'充值人数':'充值人数',
		'今天发布':'今天发布',
		'请上传审核凭证':'请上传审核凭证',
		'单任务':'单任务',
		'请选择任务类型':'请选择任务类型',
		'任务标题不能为空':'任务标题不能为空',
		'任务数量不能等于小零':'任务数量不能等于小零',
		'任务单价不能小零':'任务单价不能小零',
		'任务次数不能小零':'任务次数不能小零',
		'任务总价不能小零':'任务总价不能小零',
		'链接信息不能为空':'链接信息不能为空',
		'请选择任务级别':'请选择任务级别',
		'截止日期不能为空':'截止日期不能为空',
		'已复制成功':'已复制成功',
		'提示':'提示',
		'您的浏览器可能不支持，请手动复制':'您的浏览器可能不支持，请手动复制',
		'请先登录':'请先登录',
		'每日任务':'每日任务',
		'次':'次',
		'功能说明':'功能说明',
		'当前身份':'当前身份',
		'您当前的等级为':'您当前的等级为',
		'只能领取当前':'只能领取当前',
		'等级的任务':'等级的任务',
		'是否加入':'是否加入',
		'等级':'等级',
		'立即加入':'立即加入',
		'取消':'取消',
		'人已赚到':'人已赚到',
		'剩余':'剩余',
		'个名额':'个名额',
		'需求方':'需求方',
		'已付款':'已付款',
		'审核中':'审核中',
		'要求':'要求',
		'领取':'领取',
		'任务描述':'任务描述',
		'手机号不能为空或填写错误':'手机号不能为空或填写错误',
		'密码不能为空或填写错误':'密码不能为空或填写错误',
		'退出成功':'退出成功',
		'请设置真实姓名':'请设置真实姓名',
		'账号不可为空':'账号不可为空',
		'系统错误':'系统错误',
		'信用积分':'信用积分',
		'姓名不可为空':'姓名不可为空',
		'银行卡号不正确':'银行卡号不正确',
		'请选择银行类型':'请选择银行类型',
		'确定':'确定',
		'您的好友':'您的好友',
		'推荐码':'推荐码',
		'修改密码':'修改密码',
		'一键完成':'一键完成',
		'系统处理':'系统处理',
		'任务过期':'任务过期',
		'确认购买':'确认购买',

		'原登录密码':'原登录密码',
		'请输入原登录密码':'请输入原登录密码',
		'新登录密码':'新登录密码',
		'请输入新登录密码':'请输入新登录密码',
		'确认密码':'确认密码',
		'请输入确认密码':'请输入确认密码',
		'原密码不能为空':'原密码不能为空',
		'新密码不能为空':'新密码不能为空',
		'新密码不一致':'新密码不一致',
		'确认密码不能为空':'确认密码不能为空',
		'提交':'提交',

		'修改头像':'修改头像',
		'正在提交':'正在提交',
		'提交成功':'提交成功',
		'修改资金密码':'修改资金密码',
		'原资金密码':'原资金密码',
		'请输入原资金密码':'请输入原资金密码',
		'新资金密码':'新资金密码',
		'请输入新资金密码':'请输入新资金密码',
		'请输入新资金确认密码':'请输入新资金确认密码',
		'设置资金密码':'设置资金密码',
		'原资金密码不能为空':'原资金密码不能为空',
		'新资金密码不能为空':'新资金密码不能为空',
		'新资金密码不一致':'新资金密码不一致',
		'清除成功':'清除成功',
		'充值':'充值',
		'提现':'提现',
		'佣金':'佣金',
		'提成':'提成',
		'返点':'返点',
		'发布任务':'发布任务',
		'购买会员':'购买会员',
		'任务过期':'任务过期',
		'系统处理':'系统处理',
		'总价':'总价',
		'人数':'人数',
		'未付款':'未付款',
		'已付款':'已付款',
		'已失败':'已失败',
		'充':'充',
		'不限制':'不限制',
		'处理中':'处理中',
		'已成功':'已成功',
		'提':'提',
		'提现方式':'提现方式',
		'选择提现方式':'选择提现方式',
		'提现金额':'提现金额',
		'请输入提现金额':'请输入提现金额',
		'资金密码':'资金密码',
		'购买':'购买',
		'请输入资金密码':'请输入资金密码',
		'请选择提现方式':'请选择提现方式',
		'请输入提现金额':'请输入提现金额',
		'单笔最低金额为':'单笔最低金额为 ',
		'最高':'最高',
		'手续费':'手续费',
		'请先选择充值方式':'请先选择充值方式',
		'请输入充值金额':'请输入充值金额',
		'请输入转账姓名':'请输入转账姓名',
		'订单不存在':'订单不存在',
		'请选择图片':'请选择图片',
		'手机号不能为空或填写错误':'手机号不能为空或填写错误',
		'验证码不能为空':'验证码不能为空',
		'密码不能为空':'密码不能为空 ',
		'密码不一致':'密码不一致 ',
		'邀请码不能为空':'邀请码不能为空 ',
		'任务要求':'任务要求 ',
		'创建':'创建 ',
		'审核':'审核 ',
		'剩余数量':'剩余数量 ',
		'免费':'免费 ',
		'每日收益':'每日收益 ',
		'生效日期':'生效日期 ',
		'永久有效':'永久有效 ',
		'游客':'游客 ',
		'请登录':'请登录 ',
		'确定花费':'确定花费 ',
		'成为':'成为',
		'吗':'吗',
	}
}else if(language == 'en'){
	q_lang['en'] = {
		'恭喜会员':'Congratulations to',
		'获得':'for getting',
		'推广奖励':'promotion reward',
		'恭喜':'Congratulations',
		'完成':'Complete',
		'会员榜单提示':'single task today and earn ',
		'今天发布':'Release',
		'注册人数':'Registered number',
		'充值人数':'Number of top-ups',
		'请上传审核凭证':'Please upload the audit voucher',
		'单任务':'single task today',
		'每日任务次数':'Number of tasks per day',
		'可领取任务总数':'Total number of tasks available',
		'请选择任务类型':'Please select task type',
		'任务标题不能为空':'Task title cannot be empty',
		'任务数量不能等于小零':'The number of tasks cannot be equal to zero',
		'任务单价不能小零':'Task unit price cannot be small',
		'任务次数不能小零':'The number of tasks cannot be less than zero',
		'任务总价不能小零':'The total price of the task cannot be less than zero',
		'链接信息不能为空':'Link information cannot be empty',
		'请选择任务级别':'Please select task level',
		'截止日期不能为空':'Deadline cannot be empty',
		'已复制成功':'Successfully copied',
		'提示':'Tips',
		'一键完成':'One-click',
		'系统处理':'System processing',
		'任务过期':'Task expired',
		'确认购买':'Confirm the Purchase',
		'购买':'Purchase',
		'功能说明':'Function description',
		'您的浏览器可能不支持，请手动复制':'Your browser may not support, please copy manually',
		'请先登录':'please log in first',
		'每日任务':'Daily task',
		'次':'Times',
		'当前身份':'Current identity',
		'您当前的等级为':'Your current rating is ',
		'只能领取当前':'can only claim the current ',
		'等级的任务':' level task',
		'是否加入':'do you want to join ',
		'等级':' level',
		'立即加入':'Join now',
		'审核中':'under review',
		'取消':'Cancel',
		'人已赚到':'Man has earned it',
		'剩余':'Remaining',
		'个名额':'places',
		'需求方':'Demand side',
		'已付款':'Paid',
		'要求':'Request',
		'领取':'Receiving',
		'任务描述':'Task description',
		'手机号不能为空或填写错误':'The phone number cannot be empty or filled in incorrectly',
		'密码不能为空或填写错误':'Password cannot be empty or filled in incorrectly',
		'退出成功':'exit successfully',
		'请设置真实姓名':'Please set real name',
		'账号不可为空':'Account cannot be empty',
		'系统错误':'system error',
		'信用积分':'Credit score',
		'姓名不可为空':'Name cannot be empty',
		'银行卡号不正确':'Incorrect bank card number',
		'请选择银行类型':'Please select bank type',
		'确定':'confirm',
		'您的好友':'Your best friend',
		'推荐码':'Referral code',
		'修改密码':'change Password',

		'原登录密码':'Original login password',
		'请输入原登录密码':'Please enter the original login password',
		'新登录密码':'New login password',
		'请输入新登录密码':'Please enter the new login password',
		'确认密码':'confirm password',
		'请输入确认密码':'Please enter confirm password',
		'原密码不能为空':'The original password cannot be empty',
		'新密码不能为空':'New password cannot be empty',
		'新密码不一致':'New passwords are not consistent',
		'确认密码不能为空':'confirm password can not be blank',
		'提交':'submit',

		'修改头像':'Modify avatar',
		'正在提交':'submitting',
		'提交成功':'Submitted successfully',
		'修改资金密码':'Change fund password',
		'原资金密码':'Original fund password',
		'请输入原资金密码':'Please enter the original fund password',
		'新资金密码':'New fund password',
		'请输入新资金密码':'Please enter the new fund password',
		'请输入新资金确认密码':'Please enter the new fund confirmation password',
		'设置资金密码':'Set fund password',
		'原资金密码不能为空':'The original fund password cannot be empty',
		'新资金密码不能为空':'New fund password cannot be empty',
		'新资金密码不一致':'New fund password is inconsistent',
		'清除成功':'Cleared successfully',
		'充值':'Recharge',
		'提现':'Withdraw',
		'佣金':'Earnings',
		'提成':'Commission',
		'返点':'Rebate',
		'发布任务':'Post task',
		'购买会员':'Buy membership',
		'任务过期':'Task expired',
		'系统处理':'System processed',
		'总价':'Total price',
		'人数':'Number of people',
		'未付款':'Unpaid',
		'已失败':'Failed',
		'充':'R',
		'处理中':'Processing',
		'已成功':'succeeded',
		'提':'W',
		'提现方式':'Withdrawal method',
		'选择提现方式':'Choose withdrawal method',
		'提现金额':'Withdrawal Amount',
		'请输入提现金额':'Please enter the withdrawal amount',
		'资金密码':'Fund password',
		'请输入资金密码':'Please enter fund password',
		'请选择提现方式':'Please select the withdrawal method',
		'请输入提现金额':'Please enter the withdrawal amount',
		'单笔最低金额为':'Single minimum amount is ',
		'最高':'maximum ',
		'手续费':'handling fee ',
		'请先选择充值方式':'Please select the recharge method first',
		'请输入充值金额':'Please enter the recharge amount',
		'请输入转账姓名':'Please enter the transfer name',
		'订单不存在':'Order does not exist',
		'请选择图片':'Please choose a picture',
		'手机号不能为空或填写错误':'The phone number cannot be empty or filled in incorrectly',
		'验证码不能为空':'verification code must be filled',
		'密码不能为空':'password can not be blank ',
		'密码不一致':'Inconsistent passwords ',
		'邀请码不能为空':'Invitation code cannot be empty ',
		'任务要求':'Task requirements ',
		'创建':'Create ',
		'不限制':'not limited',
		'审核':'Audit ',
		'剩余数量':'The remaining amount ',
		'免费':'free ',
		'每日收益':'Daily income ',
		'生效日期':'effective date ',
		'永久有效':'Permanent',
		'游客':'Tourist',
		'请登录':'please sign in',
		'确定花费':'Are you sure to spend ',
		'成为':' to become ',
		'吗':'',




	}
}else if(language == 'vi'){
	q_lang['vi'] = {
		'恭喜会员':'Chúc mừng thành viên ',
		'获得':'đã nhận được phần thưởng giới thiệu ',
		'推广奖励':'Nhân dân tệ',
		'恭喜':'Chúc mừng thành viên ',
		'完成':'hôm nay đã hoàn thành ',
		'会员榜单提示':'nhiệm vụ và nhận được thu nhập ',
		'今天发布':'Hôm nay đã phát hành ',
		'单任务':' nhiệm vụ',
		'注册人数':'Số đăng ký',
		'充值人数':'Số lần nạp tiền',
		'请上传审核凭证':'Vui lòng tải lên biên bản kiểm toán',
		'每日任务次数':'Số lượng nhiệm vụ mỗi ngày',
		'可领取任务总数':'Tổng số nhiệm vụ khả dụng',
		'请选择任务类型':'Hãy chọn loại nhiệm vụ',
		'任务标题不能为空':'Không được để trống tiêu đề nhiệm vụ',
		'任务数量不能等于小零':'Số lượng nhiệm vụ không được bằng 0',
		'任务单价不能小零':'Đơn giá nhiệm vụ không được nhỏ hơn 0',
		'任务次数不能小零':'Số lần nhiệm vụ không được nhỏ hơn 0',
		'任务总价不能小零':'Tổng giá trị nhiệm vụ không được nhỏ hơn 0',
		'链接信息不能为空':'Không được để trống thông tin liên kết',
		'请选择任务级别':'Hãy chọn cấp nhiệm vụ',
		'截止日期不能为空':'Không được để trống ngày tháng kết thúc',
		'已复制成功':'Đã sao chép thành công',
		'提示':'Nhắc nhở',
		'一键完成':'Hoàn thành bằng một nút bấm',
		'系统处理':'Hệ thống xử lý',
		'任务过期':'Nhiệm vụ đã hết hạn',
		'确认购买':'Xác nhận mua',
		'购买':'Mua',
		'您的浏览器可能不支持，请手动复制':'Trình duyệt của bạn có thể không hỗ trợ, hãy sao chép thủ công',
		'请先登录':'Hãy đăng nhập trước',
		'每日任务':'Nhiệm vụ hàng ngày',
		'功能说明':'Giải thích chức năng',
		'次':'Times',
		'当前身份':'Danh tính hiện tại',
		'您当前的等级为':'Cấp hiện tại của bạn là',
		'只能领取当前':'Chỉ có thể nhận nhiệm vụ ',
		'等级的任务':' hiện tại',
		'是否加入':'Có tham gia không',
		'等级':'Cấp',
		'立即加入':'Tham gia ngay',
		'取消':'Hủy bỏ',
		'人已赚到':' người đã kiếm được',
		'剩余':'Còn lại ',
		'个名额':' người',
		'审核中':'đang xem xét',
		'需求方':'Bên có nhu cầu',
		'已付款':'Đã trả tiền',
		'要求':'Yêu cầu',
		'领取':'Nhận',
		'任务描述':'Mô tả nhiệm vụ',
		'手机号不能为空或填写错误':'Không được để trống hoặc điền sai số điện thoại di động',
		'密码不能为空或填写错误':'Không được để trống hoặc điền sai mật khẩu',
		'退出成功':'Thoát thành công',
		'请设置真实姓名':'Hãy thiết lập họ tên thật',
		'账号不可为空':'Không được để trống số tài khoản',
		'系统错误':'Lỗi hệ thống',
		'信用积分':'Điểm tín dụng',
		'姓名不可为空':'Không được để trống họ tên',
		'银行卡号不正确':'Số thẻ ngân hàng không chính xác',
		'请选择银行类型':'Hãy chọn loại ngân hàng',
		'确定':'Xác nhận',
		'您的好友':'Bạn bè của bạn',
		'推荐码':'Mã giới thiệu',
		'修改密码':'Đổi mật khẩu',

		'原登录密码':'Mật khẩu đăng nhập ban đầu',
		'请输入原登录密码':'Hãy nhập mật khẩu đăng nhập ban đầu',
		'新登录密码':'Mật khẩu đăng nhập mới',
		'请输入新登录密码':'Hãy nhập mật khẩu đăng nhập mới',
		'确认密码':'Mật khẩu xác nhận',
		'请输入确认密码':'Hãy nhập mật khẩu xác nhận',
		'原密码不能为空':'Không được để trống mật khẩu ban đầu',
		'新密码不能为空':'Không được để trống mật khẩu mới',
		'新密码不一致':'Mật khẩu mới không đồng nhất',
		'确认密码不能为空':'Không được để trống mật khẩu xác nhận',
		'提交':'Gửi đi',

		'修改头像':'Sửa hình đại diện',
		'正在提交':'Đang gửi',
		'提交成功':'Gửi thành công',
		'修改资金密码':'Sửa mật khẩu vốn',
		'原资金密码':'Mật khẩu vốn ban đầu',
		'请输入原资金密码':'Hãy nhập mật khẩu vốn ban đầu',
		'新资金密码':'Mật khẩu vốn mới',
		'请输入新资金密码':'Hãy nhập mật khẩu vốn mới',
		'请输入新资金确认密码':'Hãy nhập mật khẩu xác nhận vốn mới',
		'设置资金密码':'Cài đặt mật khẩu vốn',
		'原资金密码不能为空':'Không được để trống mật khẩu vốn ban đầu',
		'新资金密码不能为空':'Không được để trống mật khẩu vốn mới',
		'新资金密码不一致':'Mật khẩu vốn mới không đồng nhất',
		'清除成功':'Xóa thành công',
		'充值':'Nạp tiền',
		'提现':'Rút tiền',
		'佣金':'Tiền hoa hồng',
		'提成':'Tiền hoa hồng',
		'返点':'Chiết khấu',
		'发布任务':'Phát hành nhiệm vụ',
		'购买会员':'Mua tư cách thành viên',
		'任务过期':'Nhiệm vụ đã hết hạn',
		'系统处理':'Hệ thống xử lý',
		'总价':'Tổng giá trị',
		'人数':'Số người',
		'未付款':'Chưa thanh toán',
		'已失败':'Đã thất bại',
		'充':'R',
		'处理中':'Đang xử lý',
		'已成功':'Đã thành công',
		'提':'W',
		'提现方式':'Phương thức rút tiền',
		'选择提现方式':'Chọn phương thức rút tiền',
		'提现金额':'Số tiền rút',
		'请输入提现金额':'Hãy nhập số tiền rút',
		'资金密码':'Mật khẩu vốn',

		'请输入资金密码':'Hãy nhập mật khẩu vốn',
		'请选择提现方式':'Hãy chọn phương thức rút tiền',
		'请输入提现金额':'Hãy nhập số tiền rút',
		'单笔最低金额为':'Số tiền tối thiểu mỗi khoản là ',
		'最高':'Cao nhất ',
		'手续费':'Phí thủ tục ',
		'请先选择充值方式':'Hãy chọn trước phương thức nạp tiền',
		'请输入充值金额':'Hãy nhập số tiền nạp',
		'请输入转账姓名':'Hãy nhập họ tên chuyển khoản',
		'订单不存在':'Lệnh không tồn tại',
		'请选择图片':'Hãy chọn ảnh',
		'验证码不能为空':'Không được để trống mã xác thực',
		'密码不能为空':'Không được để trống mật khẩu ',
		'密码不一致':'Mật khẩu không đồng nhất ',
		'邀请码不能为空':'Không được để trống mã mời ',
		'任务要求':'Yêu cầu nhiệm vụ ',
		'创建':'Tạo ',
		'不限制':'không giới hạn',
		'审核':'Thẩm duyệt ',
		'剩余数量':'Số lượng còn lại ',
		'免费':'Miễn phí ',
		'每日收益':'Thu nhập mỗi ngày ',
		'生效日期':'Ngày tháng có hiệu lực ',
		'永久有效':'Có hiệu lực vĩnh viễn ',
		'游客':'Khách du lịch ',
		'请登录':'Hãy đăng nhập ',
		'确定花费':'Xác định trả ',
		'成为':'Nhân dân tệ trở thành ',
		'吗':'',
	}
}else if(language == 'id'){
	q_lang['id'] = {
		'恭喜会员':'Selamat,  ',
		'获得':'Anda telah mendapatkan ',
		'推广奖励':' untuk hadiah promosi',
		'恭喜':'Selamat, ',
		'完成':'Anda telah menyelesaikan ',
		'会员榜单提示':' tugas hari ini dan mendapatkan ',
		'今天发布':'Lepaskan ',
		'单任务':' tugas hari ini',
		'注册人数':'Nomor terdaftar',
		'请上传审核凭证':'Silakan mengunggah voucher audisi',
		'充值人数':'Jumlah top-up',
		'每日任务次数':'Jumlah tugas per hari',
		'可领取任务总数':'Jumlah total tugas yang tersedia',
		'请选择任务类型':'Pilih jenis tugas',
		'任务标题不能为空':'Task title cannot be empty',
		'任务数量不能等于小零':'Judul tugas tidak boleh nol',
		'任务单价不能小零':'Harga unit tugas tidak boleh lebih kecil dari nol',
		'任务次数不能小零':'Jumlah tugas tidak boleh kurang dari nol',
		'任务总价不能小零':'Harga total tugas tidak boleh kurang dari nol',
		'链接信息不能为空':'Informasi link tidak boleh kosong',
		'请选择任务级别':'Pilih tingkat tugas',
		'截止日期不能为空':'Tenggat waktu tidak boleh kosong',
		'已复制成功':'Berhasil disalin',
		'提示':'Tip',
		'一键完成':'Selesai sekali klik',
		'系统处理':'Pemrosesan sistem',
		'任务过期':'Tugas kedaluwarsa',
		'确认购买':'Konfirmasi pembelian',
		'购买':'Membeli',
		'功能说明':'Penjelasan fungsi',
		'您的浏览器可能不支持，请手动复制':'Browser Anda mungkin tidak mendukungnya, harap salin secara manual',
		'请先登录':'silahkan masuk dahulu',
		'每日任务':'Tugas sehari hari',
		'次':'Kali',
		'当前身份':'Identitas saat ini',
		'审核中':'sedang ditinjau',
		'您当前的等级为':'Peringkat anda saat ini adalah  ',
		'只能领取当前':'hanya dapat mengklaim tugas ',
		'等级的任务':' tingkat saat ini',
		'是否加入':'Apakah kamu ingin bergabung',
		'等级':' tingkat',
		'立即加入':'Bergabung sekarang',
		'取消':'Membatalkan',
		'人已赚到':' orang telah mendapatkannya',
		'剩余':'Sisa kuota ',
		'个名额':' orang',
		'需求方':'Sisi permintaan',
		'已付款':'Dibayar',
		'要求':'Permintaan',
		'领取':'Menerima',
		'任务描述':'Deskripsi tugas',
		'手机号不能为空或填写错误':'Nomor telepon tidak boleh dibiarkan kosong atau diisi dengan tidak benar',
		'密码不能为空或填写错误':'Kata sandi tidak boleh dibiarkan kosong atau diisi dengan tidak benar',
		'退出成功':'keluar dengan sukses',
		'请设置真实姓名':'Harap tetapkan nama asli Anda',
		'账号不可为空':'Akun tidak boleh kosong',
		'系统错误':'kesalahan sistematis',
		'信用积分':'Nilai kredit',
		'姓名不可为空':'Nama tidak boleh kosong',
		'银行卡号不正确':'Nomor kartu bank salah',
		'请选择银行类型':'Pilih jenis bank',
		'确定':'Konfirmasi',
		'您的好友':'Sahabatmu ',
		'推荐码':'Kode rujukan',
		'修改密码':'ganti kata sandi',

		'原登录密码':'Kata sandi login asli',
		'请输入原登录密码':'Silakan masukkan kata sandi login asli',
		'新登录密码':'Kata sandi login baru',
		'请输入新登录密码':'Silakan masukkan kata sandi login baru',
		'确认密码':'confirm password',
		'请输入确认密码':'Please enter confirm password',
		'原密码不能为空':'he original password cannot be empty',
		'新密码不能为空':'New password cannot be empty',
		'新密码不一致':'New passwords are not consistent',
		'确认密码不能为空':'confirm password can not be blank',
		'提交':'Kirimkan',

		'修改头像':'Modifikasi avatar',
		'正在提交':'mengirimkan',
		'提交成功':'Berhasil dikirim',
		'修改资金密码':'Ubah kata sandi dana',
		'原资金密码':'Kata sandi dana asli',
		'请输入原资金密码':'Silakan masukkan password dana asli',
		'新资金密码':'Kata sandi dana baru',
		'请输入新资金密码':'Silakan masukkan kata sandi dana baru',
		'请输入新资金确认密码':'Silakan masukkan kata sandi konfirmasi dana baru',
		'设置资金密码':'Tetapkan kata sandi dana',
		'原资金密码不能为空':'Kata sandi dana asli tidak boleh kosong',
		'新资金密码不能为空':'Kata sandi dana baru tidak boleh kosong',
		'新资金密码不一致':'Kata sandi dana baru tidak konsisten',
		'清除成功':'Berhasil dibersihkan',
		'充值':'Isi ulang',
		'提现':'Penarikan',
		'佣金':'Penghasilan',
		'提成':'Komisi',
		'返点':'Rebate',
		'发布任务':'Kirim tugas',
		'购买会员':'Beli keanggotaan',
		'任务过期':'Tugas kedaluwarsa',
		'系统处理':'Pemrosesan sistem',
		'总价':'Harga total',
		'人数':'Jumlah orang',
		'未付款':'Belum dibayar',
		'已失败':'Gagal',
		'充':'R',
		'处理中':'Memproses',
		'已成功':'berhasil',
		'提':'W',
		'提现方式':'Metode penarikan',
		'选择提现方式':'Pilih metode penarikan',
		'提现金额':'Jumlah Penarikan',
		'请输入提现金额':'Silakan masukkan jumlah penarikan',
		'资金密码':'Kata sandi dana',

		'请输入资金密码':'Silakan masukkan kata sandi dana',
		'请选择提现方式':'Silakan pilih metode penarikan',
		'请输入提现金额':'Silakan masukkan jumlah penarikan',
		'单笔最低金额为':'Jumlah minimum tunggal adalah ',
		'最高':'maksimum ',
		'手续费':'biaya penanganan ',
		'请先选择充值方式':'Silakan pilih metode isi ulang dulu',
		'请输入充值金额':'Silakan masukkan jumlah isi ulang',
		'请输入转账姓名':'Silakan masukkan nama transfer',
		'订单不存在':'Order tidak ada',
		'不限制':'tidak terbatas',
		'请选择图片':'Silakan pilih gambar',
		'验证码不能为空':'kode verifikasi harus diisi',
		'密码不能为空':'kode verifikasi tidak boleh kosong ',
		'密码不一致':'Kata sandi tidak konsisten ',
		'邀请码不能为空':'Kode undangan tidak boleh kosong ',
		'任务要求':'Persyaratan tugas',
		'创建':'Buat ',
		'审核':'Audit ',
		'剩余数量':'Jumlah yang tersisa ',
		'免费':'Gratis',
		'每日收益':'Penghasilan harian ',
		'生效日期':'tanggal berlaku',
		'永久有效':'Permanen',
		'游客':'tamu',
		'请登录':'silahkan masuk ',
		'确定花费':'Apakah Anda yakin menghabiskan ',
		'成为':' untuk menjadi ',
		'吗':'',
	}
}else if(language == 'hi'){
	q_lang['hi'] = {
		'恭喜会员':'सदस्यों को बधाई ',
		'获得':'प्राप्त ',
		'推广奖励':' प्रमोशन का इनाम',
		'恭喜':'उस सदस्य को',
		'完成':'बधाई जिसने आज  ',
		'会员榜单提示':' कार्य समाप्त किए और ',
		'会员榜单提示2':' युआन का लाभ प्राप्त किया',
		'今天发布':'आज जारी किया ',
		'请上传审核凭证':'कृपया ऑडिट वाचर अपलोड करें',
		'每日任务次数':'प्रति दिन कार्यों की संख्या',
		'可领取任务总数':'उपलब्ध कार्यों की कुल संख्या',
		'不限制':'सीमित नहीं',
		'注册人数':'पंजीकृत नंबर',
		'充值人数':'टॉप-अप की संख्या',
		'单任务':' कार्य',
		'请选择任务类型':'कृपया कार्य प्रकार चुनें',
		'任务标题不能为空':'टास्क शीर्षक रिक्त नहीं हो सकता',
		'任务数量不能等于小零':'कार्यों की संख्या शून्य से कम नहीं हो सकती',
		'任务单价不能小零':'टास्क यूनिट की कीमत शून्य से कम नहीं हो सकती',
		'任务次数不能小零':'कार्यों की संख्या शून्य से कम नहीं हो सकती',
		'任务总价不能小零':'कार्य की कुल कीमत शून्य से कम नहीं हो सकती',
		'链接信息不能为空':'लिंक की जानकारी रिक्त नहीं हो सकती',
		'请选择任务级别':'कृपया कार्य का स्तर चुनें',
		'截止日期不能为空':'समय सीमा रिक्त नहीं हो सकती',
		'已复制成功':'सफलतापूर्वक कॉपी किया गया',
		'提示':'टिप्स',
		'功能说明':'फ़ंक्शन विवरण',
		'一键完成':'एक-क्लिक पूरा',
		'系统处理':'सिस्टम प्रसंस्करण',
		'任务过期':'कार्य समाप्त हो गया',
		'确认购买':'खरीदी की पुष्टि करें',
		'购买':'खरीद',
		'您的浏览器可能不支持，请手动复制':'आपका ब्राउज़र समर्थन नहीं हो सकता है, कृपया मैन्युअल रूप से कॉपी करें',
		'请先登录':'कृपया पहले लॉगइन करें',
		'每日任务':'दैनिक कार्य',
		'次':'टाइम्स',
		'当前身份':'वर्तमान पहचान',
		'您当前的等级为':'आपका वर्तमान स्तर है  ',
		'只能领取当前':'केवल करंट प्राप्त कर सकते हैं ',
		'等级的任务':' स्तर का कार्य',
		'是否加入':'चाहे सम्मिलित हों',
		'等级':' स्तर',
		'立即加入':'अब सम्मिलित हैं',
		'取消':'रद्द करें',
		'人已赚到':' आदमी कमाया है',
		'剩余':'शेष',
		'个名额':' स्थान शेष',
		'需求方':'माँग पक्ष',
		'审核中':'समीक्षाधीन',
		'已付款':'सशुल्क',
		'要求':'अनुरोध',
		'领取':'प्राप्त करें',
		'任务描述':'कार्य विवरण',
		'手机号不能为空或填写错误':'फोन नंबर रिक्त या गलत तरीके से भरा नहीं जा सकता',
		'密码不能为空或填写错误':'पासवर्ड रिक्त या गलत तरीके से भरा नहीं जा सकता',
		'退出成功':'सफलतापूर्वक बाहर निकलें',
		'请设置真实姓名':'कृपया वास्तविक नाम सेट करें',
		'账号不可为空':'खाता रिक्त नहीं हो सकता',
		'系统错误':'सिस्टम गलत है',
		'信用积分':'क्रेडिट स्कोर',
		'姓名不可为空':'नाम रिक्त नहीं हो सकता',
		'银行卡号不正确':'बैंक कार्ड नंबर गलत है',
		'请选择银行类型':'कृपया बैंक प्रकार चुनें',
		'确定':'पुष्टि करें',
		'您的好友':'आपका दोस्त ',
		'推荐码':'रेफरल कोड',
		'修改密码':'पासवर्ड बदलें',

		'原登录密码':'मूल लॉगिन पासवर्ड',
		'请输入原登录密码':'कृपया मूल लॉगिन पासवर्ड दर्ज करें',
		'新登录密码':'नया लॉगिन पासवर्ड',
		'请输入新登录密码':'कृपया नया लॉगिन पासवर्ड दर्ज करें',
		'确认密码':'पासवर्ड की पुष्टि करें',
		'请输入确认密码':'कृपया पासवर्ड दर्ज करें',
		'原密码不能为空':'मूल पासवर्ड रिक्त नहीं हो सकता',
		'新密码不能为空':'नया पासवर्ड रिक्त नहीं हो सकता',
		'新密码不一致':'नए पासवर्ड सुसंगत नहीं हैं',
		'确认密码不能为空':'पुष्टि पासवर्ड रिक्त नहीं हो सकता',
		'提交':'प्रस्तुत',
		'修改头像':'अवतार संशोधित करें',
		'正在提交':'सबमिट कर रहा है',
		'提交成功':'सफलतापूर्वक सबमिट किया है',
		'修改资金密码':'निधि  पासवर्ड बदलें',
		'原资金密码':'मूल निधि पासवर्ड',
		'请输入原资金密码':'कृपया मूल निधि पासवर्ड दर्ज करें',
		'新资金密码':'नया निधि पासवर्ड',
		'请输入新资金密码':'कृपया नया निधि पासवर्ड दर्ज करें',
		'请输入新资金确认密码':'कृपया नया निधि पुष्टि पासवर्ड दर्ज करें',
		'设置资金密码':'फंड पासवर्ड सेट करें',
		'原资金密码不能为空':'मूल फंड पासवर्ड रिक्त नहीं हो सकता',
		'新资金密码不能为空':'नया फंड पासवर्ड रिक्त नहीं हो सकता',
		'新资金密码不一致':'नया फंड पासवर्ड असंगत है',
		'清除成功':'सफलतापूर्वक साफ़ किया है',
		'充值':'रिचार्ज',
		'提现':'निकालें',
		'佣金':'कमीशन',
		'提成':'आयोग',
		'返点':'कमीशन',
		'发布任务':'पोस्ट कार्य करें',
		'购买会员':'सदस्यता खरीदें',
		'任务过期':'कार्य समाप्त हो गया',
		'系统处理':'सिस्टम प्रसंस्करण',
		'总价':'कुल मूल्य',
		'人数':'लोगों की संख्या',
		'未付款':'अवैतनिक',
		'已失败':'विफल',
		'充':'R',
		'处理中':'संसाधित कर रहा है',
		'已成功':'सफल',
		'提':'W',
		'提现方式':'निकासी विधि',
		'选择提现方式':'निकासी विधि चुनें',
		'提现金额':'निकासी राशि',
		'请输入提现金额':'कृपया निकासी राशि दर्ज करें',
		'资金密码':'फंड पासवर्ड',

		'请输入资金密码':'कृपया पासवर्ड दर्ज करें',
		'请选择提现方式':'कृपया निकासी निकासी विधि का चयन करें',
		'请输入提现金额':'कृपया विद्ड्रॉअल राशि दर्ज करें',
		'单笔最低金额为':'एकल न्यूनतम राशि है ',
		'最高':'अधिकतम ',
		'手续费':'हैंडलिंग शुल्क ',
		'请先选择充值方式':'कृपया पहले रिचार्ज विधि चुनें',
		'请输入充值金额':'कृपया रिचार्ज राशि दर्ज करें',
		'请输入转账姓名':'कृपया ट्रांसफर नाम दर्ज करें',
		'订单不存在':'ऑर्डर मौजूद नहीं है',
		'请选择图片':'कृपया एक चित्र चुनें',
		'验证码不能为空':'सत्यापन कोड भरना होगा',
		'密码不能为空':'पासवर्ड रिक्त नहीं हो सकता ',
		'密码不一致':'असंगत पासवर्ड ',
		'邀请码不能为空':'निमंत्रण कोड रिक्त नहीं हो सकता ',
		'任务要求':'कार्य आवश्यकताएँ',
		'创建':'बनाएँ ',
		'审核':'ऑडिट ',
		'剩余数量':'शेष राशि ',
		'免费':'मुक्त',
		'每日收益':'दैनिक आय ',
		'生效日期':'प्रभावी तिथि',
		'永久有效':'स्थायी',
		'游客':'पर्यटक',
		'请登录':'कृपया साइन इन करें',
		'确定花费':'युआन खर्च करने का दृढ़ संकल्प ',
		'成为':' बनने के लिए ',
		'吗':'',
	}
}


